openapi: 3.0.3
info:
  title: Related Visitors API
  description: |
    Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
    Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
  version: '3'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
