# Use this file to specify the schema for the error responses that are shared between several APIs.
# For example, the schema for HTTP error 429 is the same for Delete API, Related Visitors API, etc.

openapi: 3.0.3
info:
  title: Schema for error responses
  version: '1'
components:
  schemas:
    400ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: 'object'
          additionalProperties: false
          properties:
            code:
              type: string
              description: >
                Error code:
                * `RequestCannotBeParsed` - The visitor ID parameter is missing or in the wrong format.
              enum:
                - RequestCannotBeParsed
              example: 'RequestCannotBeParsed'
            message:
              type: string
              example: 'invalid visitor id'
          required:
            - code
            - message
    403ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: 'object'
          additionalProperties: false
          properties:
            code:
              type: string
              description: >
                Error code:
                 * `TokenRequired` - `Auth-API-Key` header is missing or empty
                 * `TokenNotFound` - No Fingerprint application found for specified secret key
                 * `SubscriptionNotActive` - Fingerprint application is not active
                 * `WrongRegion` - server and application region differ
                 * `FeatureNotEnabled` - this feature (for example, Delete API) is not enabled for your application 
              enum:
                - TokenRequired
                - TokenNotFound
                - SubscriptionNotActive
                - WrongRegion
                - FeatureNotEnabled
              example: 'TokenRequired'
            message:
              type: string
              example: 'secret key is required'
          required:
            - code
            - message
    404ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: 'object'
          additionalProperties: false
          properties:
            code:
              type: string
              description: >
                Error code:
                * `VisitorNotFound` - The specified visitor ID was not found. It never existed or it may have already been deleted.
              enum:
                - VisitorNotFound
              example: 'VisitorNotFound'
            message:
              type: string
              example: 'visitor not found'
          required:
            - code
            - message
    429ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: 'object'
          additionalProperties: false
          properties:          
            code:
              type: string
              description: >
                Error code:
                * `TooManyRequests` - The request is throttled.
              enum:
                - TooManyRequests
              example: 'TooManyRequests'
            message:
              type: string
              example: 'request throttled'
          required:
            - code
            - message        

            
            
    
      
