name: Publish schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    name: Publish
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/test-and-build
        with:
          visitorId: '${{ secrets.VISITOR_ID }}'
          privateKey: '${{ secrets.PRIVATE_KEY }}'
          requestId: '${{ secrets.REQUEST_ID }}'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          branch: gh-pages
          folder: dist
