# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on:
  workflow_call:
  pull_request:
jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/test-and-build
        with:
          visitorId: '${{ secrets.VISITOR_ID }}'
          privateKey: '${{ secrets.PRIVATE_KEY }}'
          requestId: '${{ secrets.REQUEST_ID }}'
