# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Validate
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  validate:
    uses: ./.github/workflows/test.yml