# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 3
    env:
      VISITOR_ID: '${{ secrets.VISITOR_ID }}'
      PRIVATE_KEY: '${{ secrets.PRIVATE_KEY }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            !**/dist/node_modules
          key: nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: nodemodules-
      - name: Install Node packages
        run: yarn install
      - name: Validate schema
        run: yarn validateSchema